# Alacritty Configuration

[env]
# WSL側で正しくキーシーケンスが解釈されるよう、xterm-256colorを指定します
TERM = "xterm-256color"

# 2. キーバインディングの設定
[keyboard]
bindings = [
    # F11で全画面表示の切り替え
    { key = "F11", action = "ToggleFullscreen" },
    
    # 必要に応じて：コピー＆ペーストをCtrl+C/Vで行いたい場合
    { key = "C", mods = "Shift|Control", action = "Copy" },

    { key = "V", mods = "Shift|Control", action = "Paste" }
]

[window]

# 起動時のウィンドウサイズ（任意）
dimensions = { columns = 100, lines = 30 }

# ウィンドウの不透明度 (0.0 〜 1.0)
opacity = 0.95



[terminal.shell]
program = "/Windows/System32/wsl.exe ~ -d Ubuntu-24.04 bash -ic tmux"



[font]
size = 12

[font.normal]
family = "Moralerspace Argon HWNF"
style = "Regular"


[font.bold]
family = "Moralerspace Argon HWNF"
style = "Bold"

[font.italic]
family = "Moralerspace Argon HWNF"
style = "Italic"

[font.bold_italic]
family = "Moralerspace Argon HWNF"

style = "Bold Italic"


# Gruvbox Dark Theme
[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"


[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"

white   = "#ebdbb2"
